feat: include lobbyToken in GET lobby/:id response
UCLA-Creative-Labs/aurgy-backend pull request #42
Opened 2022-03-03 07:31 UTC by darren2hang

Small change: The lobbyToken of the lobby is included in the response to lobby/:id GET

2022-03-03 21:02 UTC, BryanPan342 commented on www/lobby/id.ts
> +  res.status(200).json({...lobby.getClientResponse(), lobbyToken: lobbyToken});
only if the user is the manager!

2022-03-03 23:29 UTC, BryanPan342 requested changes
me thinks this is cleaner

2022-03-03 23:29 UTC, BryanPan342 commented on www/lobby/id.ts
> +  res.status(200).json(resObj);
```suggestion
  res.status(200).json(userId === lobby.managerId
    ? lobby.getClientResponse()
    : {...lobby.getClientResponse, lobbyToken: genJwt(lobbyId, EXPIRATION.ONE_HOUR}
```

2022-03-03 23:48 UTC, BryanPan342 submitted a review, later dismissed
LGTM

2022-03-04 00:17 UTC, trevorong approved these changes
lgtm

2022-03-04 00:18 UTC, merged